server:
  port: ${PORT:8081}

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456
    initialize: true
    maxActive: 3

  sql:
    init:
      mode:
      continue-on-error: true
      platform: postgresql

  jpa:
    hibernate:
      ddl-auto: create-drop #desabilitar o ddl-auto em caso de ambiente de produção. Pq ele sempre dropa a tabela quando a aplicação é parada.
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect #Precisei rodar um dialeto mais atual, a versão 9 não estava funcionando.

app-config:
  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=}

